########################### Chapetr 7 - Lab 3 GAMs #########################

library(ISLR) ##For Wage dataset.
library(splines)
##install.packages("gam") - To install gam library.
library(gam) ##To fit GAMs like smoothing spline which cannot be expresses as basis functions.
install.packages("akima")
library(akima) ##Used to plot the two diamensional surface generated by performing two diamensional local regression. 

attach(Wage) ##Attach Wage data set.
?Wage
dim(Wage) ##a 3000 x 12 data frame.
summary(Wage)
str(Wage)
fix(Wage)

agelims =range(age) ##Gets the range for the variable age.
agelims ##Range =[18, 80]
age.grid =seq(from=agelims[1], to=agelims[2]) ##Generates a set of integers from 18 to 60.
length(age.grid) ##Length 63

## We now fit a GAM to predict wage using natural spline functions of year and age, treating education as a qualitative predictor

gam1 =lm(wage~ns(age, 5)+ns(year, 4)+education, data=Wage)

##We now fit the model using smoothing splines rather than natural splines.
##In order to fit more general sorts of GAMs, using smoothing splines or other components that
##cannot be expressed in the form of basis functions and the fit using least square regression,
##we need to use the gam library in R.

##The gam() function, part of gam library, is used to fit a GAM in such cases.
##The s() function, also part of gam library, is used to indicate smoothing splines.

gam.m3 =gam(wage~s(year, 4) + s(age, 5) + education, data=Wage) ##Here 4 & 5 are degrees of freedom.

#### Figure 7.12 ####
##In order to produce the figure 7.12, we simply call the plot function
par(mfrow =c(1, 3))
plot(gam.m3, se=TRUE, col="blue") ##The plot() function recognizes that gam.m3 is an glm object.

##We can also create the same plot using:
plot.gam(gam.m3, se=TRUE, col="blue")  

##Here the component of year look rather linear. We now perform an anova test to determine which of the following models is the best:
## 1. A GAM that excludes year - (M1)
## 2. A GAM that uses a linear function of year - (M2)
## 3. A GAM that uses a spline function of year - (M3)

gam.m1 =gam(wage~s(age, 5) + education, data =Wage)
gam.m2 =gam(wage~s(age, 5) + year + education, data =Wage)

anova(gam.m1, gam.m2, gam.m3, test ="F")

##From the results, we see that there is strong evidence that M2 is better than M1.
##However there is no evidence of M3 being better than M1.
##Based on the results of ANOVA, M2 is the preferred model.

summary(gam.m3) ##The large p value for the spline term of year reinforces our results from ANOVA.

##Next, we make predictions on the training set using predict()
preds =predict(gam.m2, newdata=Wage)

## We can also using local regression as building blocks in GAMs.
gam.lo =gam(wage~s(year, df =4) + lo(age, span =0.7) + education, data =Wage)
plot.gam(gam.lo, se =TRUE, col ="green")

##lo() function is a part of gam library.
## We can also use lo() function to create an interaction before calling the gam() function.
gam.lo.i =gam(wage~lo(year, age, span =0.5) + education, data =Wage)
##The first term is a two diamensional between year and age.
##We can plot the resulting two-diamensional surface if we install akima package.
plot(gam.lo.i)

##Next, we fit a logistic regression GAM.
gam.lr =gam(I(wage > 250)~year + s(age, df =5) + education, family =binomial, data =Wage)
par(mfrow =c(1, 3))
plot(gam.lr, se =T, col ="green") ##Figure 7.13

table(education, I(wage>250))
## There are no high earners in the data set for the education category "<HS Grad".
## This is causing the SE for this category to be wide apart in the rightmost plot for education.

##Hence we now fit a logistic regression GAM using all but this category.
gam.lr.s =gam(I(wage > 250)~year + s(age, df =5) + education, family =binomial, data =Wage, subset =(education !="1. < HS Grad"))
plot(gam.lr.s, se =T, col ="green") ##Figure 7.14


detach(Wage)
rm(list =ls())

